- name: Install Ansible and curl
  apt:
    name: 
      - ansible
      - curl
    state: latest

- name: Install k3s
  shell: 'curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.1+k3s1 sh -s - --no-deploy=traefik'

- name: Export variable KUBECONFIG
  shell: export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

- name: Start k3s service
  service:
    name: k3s
    state: started
    enabled: yes
